Repository ImperialCollegeLondon/FLT, pull requests merged in 2025-05, with the labels that each got.

#445 feat: map a path towards completion of the adeles miniproject
  FLT/DedekindDomain/FiniteAdeleRing/BaseChange.lean
  blueprint/lean_decls
  blueprint/src/chapter/AdeleMiniproject.tex
Labels: WIP

#454 O_w is finite over O_v
  FLT/DedekindDomain/FiniteAdeleRing/BaseChange.lean
  FLT/Mathlib/Algebra/Module/Submodule/Basic.lean
  FLT/Mathlib/Topology/Algebra/Module/ModuleTopology.lean
Labels: awaiting-CI

#457 The ring of integers `v.adicCompletionIntegers K` is compact if it has finite residue field
  FLT.lean
  FLT/DedekindDomain/AdicValuation.lean
  FLT/Mathlib/Algebra/Order/GroupWithZero/Canonical.lean
  FLT/Mathlib/RingTheory/Ideal/Quotient/Basic.lean
  FLT/Mathlib/RingTheory/LocalRing/MaximalIdeal/Basic.lean
  FLT/Mathlib/RingTheory/Valuation/ValuationSubring.lean
  FLT/Mathlib/Topology/Algebra/Valued/WithZeroMulInt.lean
  FLT/NumberField/Completion/Finite.lean
Labels: awaiting-CI

#476 chore: bump and shake
  FLT/Assumptions/Mazur.lean
  FLT/Assumptions/Odlyzko.lean
  FLT/AutomorphicForm/QuaternionAlgebra/FiniteDimensional.lean
  FLT/AutomorphicForm/QuaternionAlgebra/HeckeOperators/Abstract.lean
  FLT/AutomorphicRepresentation/Example.lean
  FLT/Basic/Reductions.lean
  FLT/DedekindDomain/AdicValuation.lean
  FLT/DedekindDomain/FiniteAdeleRing/BaseChange.lean
  FLT/Deformations/Algebra/InverseLimit/Basic.lean
  FLT/Deformations/Algebra/InverseLimit/Topology.lean
  FLT/DivisionAlgebra/Finiteness.lean
  FLT/EllipticCurve/Torsion.lean
  FLT/GaloisRepresentation/Cyclotomic.lean
  FLT/HaarMeasure/DistribHaarChar/AdeleRing.lean
  FLT/Mathlib/Algebra/IsQuaternionAlgebra.lean
  FLT/Mathlib/Algebra/Module/Submodule/Basic.lean
  FLT/Mathlib/LinearAlgebra/Pi.lean
  FLT/Mathlib/NumberTheory/NumberField/Embeddings.lean
  FLT/Mathlib/RingTheory/Ideal/Quotient/Basic.lean
  FLT/Mathlib/Topology/Algebra/Valued/ValuationTopology.lean
  FLT/Mathlib/Topology/Algebra/Valued/WithZeroMulInt.lean
  FLT/NumberField/AdeleRing.lean
  FLT/NumberField/Completion/Finite.lean
  FLT/NumberField/InfiniteAdeleRing.lean
  FLT/NumberField/InfinitePlace/Extension.lean
  FLT/NumberField/InfinitePlace/WeakApproximation.lean
  FLT/Patching/System.lean
  FLT/Patching/Utils/Depth.lean
  FLT/Patching/Utils/Lemmas.lean
  lake-manifest.json
  lean-toolchain
  scripts/nolints.json
Labels: awaiting-CI

#479 L tensor K_v = \oplus_{w|v} L_w
  FLT.lean
  FLT/DedekindDomain/AdicValuation.lean
  FLT/DedekindDomain/FiniteAdeleRing/BaseChange.lean
  FLT/Mathlib/NumberTheory/RamificationInertia/Basic.lean
  FLT/Mathlib/RingTheory/TensorProduct/Basis.lean
Labels: awaiting-CI

#480 feat: relating R-module top and S-module top
  FLT/Mathlib/Topology/Algebra/Module/ModuleTopology.lean
  blueprint/lean_decls
  blueprint/src/chapter/FujisakiProject.tex
Labels: awaiting-CI

#490 chore: rename DistribHaarChar to HaarChar
  FLT.lean
  FLT/DivisionAlgebra/Finiteness.lean
  FLT/HaarMeasure/HaarChar/AdeleRing.lean
  FLT/HaarMeasure/HaarChar/Padic.lean
  FLT/HaarMeasure/HaarChar/RealComplex.lean
  FLT/HaarMeasure/HaarChar/Ring.lean
Labels: awaiting-CI

#485 feat: start to tidy Haar character blueprint; create tasks
  FLT.lean
  FLT/DivisionAlgebra/Finiteness.lean
  FLT/HaarMeasure/HaarChar/AddEquiv.lean
  FLT/HaarMeasure/HaarChar/AdeleRing.lean
  FLT/HaarMeasure/HaarChar/Ring.lean
  blueprint/lean_decls
  blueprint/src/chapter/FujisakiProject.tex
  blueprint/src/chapter/HaarCharacterProject.tex
Labels: WIP

#503 chore: fix blueprint errors
  FLT/AutomorphicForm/QuaternionAlgebra/FiniteDimensional.lean
  blueprint/lean_decls
  blueprint/src/chapter/AdeleMiniproject.tex
  blueprint/src/chapter/QuaternionAlgebraProject.tex
  blueprint/src/chapter/ch03frey.tex
  blueprint/src/chapter/ch04overview.tex
  blueprint/src/chapter/ch05automorphicformexample.tex
Labels: awaiting-CI

#525 Fujisaki: Proofs of X_meets_kernel and X_meets_kernel'
  FLT/DivisionAlgebra/Finiteness.lean
  blueprint/src/chapter/FujisakiProject.tex
Labels: awaiting-author

#533 feat: more work on restricted product Haar character stuff
  FLT.lean
  FLT/HaarMeasure/HaarChar/AddEquiv.lean
  FLT/HaarMeasure/HaarChar/Ring.lean
  FLT/Mathlib/Topology/Algebra/RestrictedProduct.lean
  blueprint/lean_decls
  blueprint/src/chapter/HaarCharacterProject.tex
Labels: awaiting-CI

#544 feat: regular_comap_of_isOpenEmbedding
  FLT.lean
  FLT/HaarMeasure/HaarChar/AddEquiv.lean
  FLT/Mathlib/MeasureTheory/Group/Action.lean
  FLT/Mathlib/MeasureTheory/Group/Measure.lean
  FLT/Mathlib/MeasureTheory/Measure/OpenPos.lean
  FLT/Mathlib/MeasureTheory/Measure/Regular.lean
  FLT/Mathlib/MeasureTheory/Measure/Typeclasses/Finite.lean
  blueprint/lean_decls
  blueprint/src/chapter/HaarCharacterProject.tex
Labels: awaiting-CI

#558 feat: prove mulEquivHaarChar_eq_mulEquivHaarChar_of_isOpenEmbedding
  FLT/HaarMeasure/HaarChar/AddEquiv.lean
  blueprint/src/chapter/HaarCharacterProject.tex
Labels: awaiting-review

#561 feat: units of restricted products are (algebraically) restricted product of the units
  FLT/Mathlib/Topology/Algebra/RestrictedProduct.lean
Labels: awaiting-CI

#580 chore: remove FLT/Hard directory and update Assumptions/README.md
  FLT.lean
  FLT/Assumptions/README.md
  FLT/Hard/Results.lean
Labels: awaiting-CI

#446 feat: concrete Hecke operators
  FLT.lean
  FLT/AutomorphicForm/QuaternionAlgebra/Defs.lean
  FLT/AutomorphicForm/QuaternionAlgebra/HeckeOperators/Abstract.lean
  FLT/AutomorphicForm/QuaternionAlgebra/HeckeOperators/Concrete.lean
  FLT/DedekindDomain/Completion/BaseChange.lean
  FLT/DedekindDomain/FiniteAdeleRing/LocalUnits.lean
  FLT/DedekindDomain/FiniteAdeleRing/TensorPi.lean
  FLT/DedekindDomain/IntegralClosure.lean
  FLT/HaarMeasure/HaarChar/FiniteDimensional.lean
  FLT/HaarMeasure/HaarChar/Ring.lean
  FLT/Mathlib/Algebra/FixedPoints/Basic.lean
  FLT/Mathlib/Topology/Algebra/Group/Units.lean
  FLT/Mathlib/Topology/Algebra/RestrictedProduct.lean
  FLT/QuaternionAlgebra/NumberField.lean
  blueprint/lean_decls
  blueprint/src/chapter/HeckeOperatorProject.tex
  blueprint/src/content.tex
  scripts/noshake.json
Labels: WIP
